### ISSUE TITLE
[WIP] タスクのokを押したときの挙動を考える

### ISSUE THREAD

**Issue by omuomugin** [runaway-org/shareTODO#20]
タスクを消したときにどういう挙動であるべきかを考える

**Comment by omuomugin** [comment]
とりあえず、2種類の状態を用意してokを押したら完了になるようにはした。

**Comment by omuomugin** [comment]
<img src=https://cloud.githubusercontent.com/assets/16621708/15523204/c1d3e4f0-2253-11e6-84c0-ca34ea2fd421.png width=320px>

<img src=https://cloud.githubusercontent.com/assets/16621708/15523205/c200a670-2253-11e6-9b23-e03c922dbdeb.png width=320px>

<img src=https://cloud.githubusercontent.com/assets/16621708/15523206/c21ecb00-2253-11e6-9d47-3bf64d565e4e.png width=320px>

@ronnnnn ちょっとわかりにくいけど、上から4番目の要素がok押したら完了になってもう一回ok押したら消えるってした

**Comment by ronnnnn** [comment]
いいね

**Comment by omuomugin** [comment]
マージ済み
