### ISSUE TITLE
[WIP] recycler viewを組み込む

### ISSUE THREAD

**Issue by omuomugin** [runaway-org/shareTODO#5]
recycler viewを組み込む

**Comment by omuomugin** [comment]
https://gist.github.com/athornz/008edacd1d3b2f1e1836

このMergeAdapterを使おうかな

**Comment by ronnnnn** [comment]
バグ残ってるみたいだけど、今回使うのには関係ない感じ？

**Comment by omuomugin** [comment]
まあ、あんまり関係ないというか起きる場合が少ないかな。
でも、これ便利そうだし使ってみようということ。
こいつを抜くときは、すぐ抜けるようにコードは書くつもり

**Comment by ronnnnn** [comment]
@omuomugin マージ完了
