### ISSUE TITLE
モデルを作成する

### ISSUE THREAD

**Issue by omuomugin** [runaway-org/shareTODO#6]
TODO
設計をしっかりと話し合って決める

**Comment by ronnnnn** [comment]
# モデル案
- User
 - userName
 - userId
- Main Task
 - mainTaskName
 - subTask
- Sub Task
 - subTaskName
 - subTaskText
 - user

**Comment by omuomugin** [comment]
Taskにはそれぞれ isCompleteのフィールドが欲しいかな。
isCompleteっていう名前は今回はあんまり適してないから、名前を考えたい。

誰も請け負ってない状態と誰かが請け負った状態を表すフィールド

**Comment by ronnnnn** [comment]
isAssignedでどう？

**Comment by omuomugin** [comment]
isAssignedで行くことに

**Comment by omuomugin** [comment]
とりあえずこれ終わってる。
